spring.application.name=SpringBooth-POS
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/pencpos
spring.datasource.username=postgres
spring.datasource.password=danielle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true